[package]
name = "zcore-catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
zcore-storage = { path = "../zcore-storage" }

[dev-dependencies]
tempfile = "3"
