[package]
name = "zsql-parser"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
sqlparser = { workspace = true }

[dev-dependencies]
rstest = "0.18"
serde_json = { workspace = true }
